### ISSUE TITLE
platform.txt

### ISSUE THREAD

**Issue by x893** [SodaqMoja/SodaqCore-samd#1]
Hi
small issua with

recipe.ar.pattern="{compiler.path}{compiler.ar.cmd}" {compiler.ar.flags} {compiler.ar.extra_flags} **"{build.path}/{archive_file}"** "{object_file}"

recipe.ar.pattern="{compiler.path}{compiler.ar.cmd}" {compiler.ar.flags} {compiler.ar.extra_flags} **"{archive_file_path}"** "{object_file}"

**Comment by janvl1234** [comment]
Hi @x893,
Looking into the source code it seems the issue was resolved some time ago. 
Can you confirm and close the issue?

**Comment by x893** [comment]
Hi @janvl1234
You can close the issue
