### ISSUE TITLE
Wrong link as part of online help

### ISSUE THREAD

**Issue by jwillemsen** [SodaqMoja/SodaqCore-samd#6]
After installing this package as part of the arduino boards manager, selecting "Online Help" redirects to forums.sodaq.com, that should be forum.sodaq.com
![screenshot_20170217_151348](https://cloud.githubusercontent.com/assets/47353/23068379/b6ad9136-f523-11e6-8587-02b67a79f21a.png)

**Comment by janvl1234** [comment]
Hi @jwillemsen , 
Thanks for letting us know. The issue has been resolved for the SAMD board in v1.8.6
