### ISSUE TITLE
SDU not working on SODAQ Sara R412.

### ISSUE THREAD

**Issue by phlegx** [SodaqMoja/SodaqCore-samd#9]
Hi!

I have a SODAQ SARA R412m board with a SD card reader attached to SPI. I want to use the SDU library but it don't work put of the box. After including `SDU.h` I get the error:

`/SODAQ/hardware/samd/1.8.6/libraries/SDU/src/SDU.cpp:44:4: error: #error "Unsupported board!"`

**Why the SODAQ libraries don't support SODAQ boards?**

Read more about here: https://forum.sodaq.com/t/firmwire-over-the-air/3205/12

**Comment by janvl1234** [comment]
Hi, 

The library has been fixed in the v1.8.9.
You can read here how to install the v1.8.9 (Beta)
https://support.sodaq.com/getting_started/

**Comment by SodaqMoja** [comment]
Version v1.8.9 is now considered stable. Please use this URL for the board files
http://downloads.sodaq.net/package_sodaq_samd_index.json
